locals {
  s3_prefix                         = "blizzard-quotes"
  s3_bucket_logs_name               = "${local.s3_prefix}-logs"
  s3_bucket_blizzard_quotes_ui_name = "${local.s3_prefix}-ui"
  s3_bucket_wc3_quotes_ui_name      = "${local.s3_prefix}-wc3-ui"
  s3_bucket_sc2_quotes_ui_name      = "${local.s3_prefix}-sc2-ui"
  s3_bucket_sc_quotes_ui_name       = "${local.s3_prefix}-sc-ui"
  s3_bucket_wc3_swagger_name        = "${local.s3_prefix}-wc3-swagger"
  s3_bucket_sc2_swagger_name        = "${local.s3_prefix}-sc2-swagger"
  s3_bucket_sc_swagger_name         = "${local.s3_prefix}-sc-swagger"

  blizzard_quotes_hostname = "blizzardquotes.com"
  wc3_hostname             = "wc3.${local.blizzard_quotes_hostname}"
  wc3_api_hostname         = "api.${local.wc3_hostname}"
  wc3_swagger_hostname     = "swagger.${local.wc3_hostname}"
  sc2_hostname             = "sc2.${local.blizzard_quotes_hostname}"
  sc2_api_hostname         = "api.${local.sc2_hostname}"
  sc2_swagger_hostname     = "swagger.${local.sc2_hostname}"
  sc_hostname              = "sc.${local.blizzard_quotes_hostname}"
  sc_api_hostname          = "api.${local.sc_hostname}"
  sc_swagger_hostname      = "swagger.${local.sc_hostname}"
}
